# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ner.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ner.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tner.proto\"\x88\x01\n\x16\x45xtractEntitiesRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x34\n\x04mode\x18\x02 \x01(\x0e\x32&.ExtractEntitiesRequest.ExtractionMode\"*\n\x0e\x45xtractionMode\x12\n\n\x06SINGLE\x10\x00\x12\x0c\n\x08\x45NSEMBLE\x10\x01\"+\n\x17\x45xtractEntitiesResponse\x12\x10\n\x08\x65ntities\x18\x01 \x03(\t\"$\n\x12RunTrainingRequest\x12\x0e\n\x06\x65pochs\x18\x01 \x01(\x05\"-\n\x13RunTrainingResponse\x12\x16\n\x0e\x65rror_messages\x18\x01 \x03(\t2\x89\x01\n\x03NER\x12\x46\n\x0f\x45xtractEntities\x12\x17.ExtractEntitiesRequest\x1a\x18.ExtractEntitiesResponse\"\x00\x12:\n\x0bRunTraining\x12\x13.RunTrainingRequest\x1a\x14.RunTrainingResponse\"\x00\x62\x06proto3'
)



_EXTRACTENTITIESREQUEST_EXTRACTIONMODE = _descriptor.EnumDescriptor(
  name='ExtractionMode',
  full_name='ExtractEntitiesRequest.ExtractionMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SINGLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ENSEMBLE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=108,
  serialized_end=150,
)
_sym_db.RegisterEnumDescriptor(_EXTRACTENTITIESREQUEST_EXTRACTIONMODE)


_EXTRACTENTITIESREQUEST = _descriptor.Descriptor(
  name='ExtractEntitiesRequest',
  full_name='ExtractEntitiesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ExtractEntitiesRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='ExtractEntitiesRequest.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXTRACTENTITIESREQUEST_EXTRACTIONMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=150,
)


_EXTRACTENTITIESRESPONSE = _descriptor.Descriptor(
  name='ExtractEntitiesResponse',
  full_name='ExtractEntitiesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entities', full_name='ExtractEntitiesResponse.entities', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=195,
)


_RUNTRAININGREQUEST = _descriptor.Descriptor(
  name='RunTrainingRequest',
  full_name='RunTrainingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='epochs', full_name='RunTrainingRequest.epochs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=233,
)


_RUNTRAININGRESPONSE = _descriptor.Descriptor(
  name='RunTrainingResponse',
  full_name='RunTrainingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_messages', full_name='RunTrainingResponse.error_messages', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=280,
)

_EXTRACTENTITIESREQUEST.fields_by_name['mode'].enum_type = _EXTRACTENTITIESREQUEST_EXTRACTIONMODE
_EXTRACTENTITIESREQUEST_EXTRACTIONMODE.containing_type = _EXTRACTENTITIESREQUEST
DESCRIPTOR.message_types_by_name['ExtractEntitiesRequest'] = _EXTRACTENTITIESREQUEST
DESCRIPTOR.message_types_by_name['ExtractEntitiesResponse'] = _EXTRACTENTITIESRESPONSE
DESCRIPTOR.message_types_by_name['RunTrainingRequest'] = _RUNTRAININGREQUEST
DESCRIPTOR.message_types_by_name['RunTrainingResponse'] = _RUNTRAININGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExtractEntitiesRequest = _reflection.GeneratedProtocolMessageType('ExtractEntitiesRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTENTITIESREQUEST,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:ExtractEntitiesRequest)
  })
_sym_db.RegisterMessage(ExtractEntitiesRequest)

ExtractEntitiesResponse = _reflection.GeneratedProtocolMessageType('ExtractEntitiesResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXTRACTENTITIESRESPONSE,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:ExtractEntitiesResponse)
  })
_sym_db.RegisterMessage(ExtractEntitiesResponse)

RunTrainingRequest = _reflection.GeneratedProtocolMessageType('RunTrainingRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNTRAININGREQUEST,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:RunTrainingRequest)
  })
_sym_db.RegisterMessage(RunTrainingRequest)

RunTrainingResponse = _reflection.GeneratedProtocolMessageType('RunTrainingResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNTRAININGRESPONSE,
  '__module__' : 'ner_pb2'
  # @@protoc_insertion_point(class_scope:RunTrainingResponse)
  })
_sym_db.RegisterMessage(RunTrainingResponse)



_NER = _descriptor.ServiceDescriptor(
  name='NER',
  full_name='NER',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=283,
  serialized_end=420,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractEntities',
    full_name='NER.ExtractEntities',
    index=0,
    containing_service=None,
    input_type=_EXTRACTENTITIESREQUEST,
    output_type=_EXTRACTENTITIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RunTraining',
    full_name='NER.RunTraining',
    index=1,
    containing_service=None,
    input_type=_RUNTRAININGREQUEST,
    output_type=_RUNTRAININGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NER)

DESCRIPTOR.services_by_name['NER'] = _NER

# @@protoc_insertion_point(module_scope)
